apiVersion: v1
kind: Secret
metadata:
  name: database
  namespace: applications
type: Opaque
stringData:
  host: "postgres-postgresql.applications.svc.cluster.local."
  port: "5432"
  user: "postgres"
  password: "postgres"
  name: "postgres"
