name: Module

on:
  push:
    tags: [ 'v*.*.*' ]

jobs:
  module:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@master
        with:
          persist-credentials: false

      - name: Setup Go 🐻
        uses: actions/setup-go@v2
        with:
          go-version: '1.14.1'

      - name: Test 🧪
        run: go version # change

      - name: Publish 🚀
        run: |
          export RELEASE_VERSION=${GITHUB_REF#refs/*/}
          curl "https://sum.golang.org/lookup/github.com/neoxelox/ssm@${RELEASE_VERSION}"
          curl "https://proxy.golang.org/github.com/neoxelox/ssm/@v/${RELEASE_VERSION}.info"
